#pragma once

#include "driver/gpio.h"
#include "driver/i2c_types.h"
#include "hal/adc_types.h"

#define BOARD_NAME "KAKATA RC433"

#define BOARD_I2C_PORT I2C_NUM_0
#define BOARD_I2C_SDA_GPIO GPIO_NUM_21
#define BOARD_I2C_SCL_GPIO GPIO_NUM_22
#define BOARD_I2C_FREQ_HZ 400000

#define BOARD_OLED_ADDR 0x3C
#define BOARD_MPU6050_ADDR 0x68

#define BOARD_JOY0_MT_GPIO GPIO_NUM_36
#define BOARD_JOY0_MT_ADC_UNIT ADC_UNIT_1
#define BOARD_JOY0_MT_ADC_CHANNEL ADC_CHANNEL_0

#define BOARD_JOY0_MD_GPIO GPIO_NUM_39
#define BOARD_JOY0_MD_ADC_UNIT ADC_UNIT_1
#define BOARD_JOY0_MD_ADC_CHANNEL ADC_CHANNEL_3

#define BOARD_JOY1_MT_GPIO GPIO_NUM_32
#define BOARD_JOY1_MT_ADC_UNIT ADC_UNIT_1
#define BOARD_JOY1_MT_ADC_CHANNEL ADC_CHANNEL_4

#define BOARD_JOY1_MD_GPIO GPIO_NUM_33
#define BOARD_JOY1_MD_ADC_UNIT ADC_UNIT_1
#define BOARD_JOY1_MD_ADC_CHANNEL ADC_CHANNEL_5

#define BOARD_JOY0_BTN_GPIO GPIO_NUM_25
#define BOARD_JOY1_BTN_GPIO GPIO_NUM_26

#define BOARD_BTN0_GPIO GPIO_NUM_13
#define BOARD_BTN1_GPIO GPIO_NUM_14
#define BOARD_BTN2_GPIO GPIO_NUM_16
#define BOARD_BTN3_GPIO GPIO_NUM_17
#define BOARD_BTN4_GPIO GPIO_NUM_18

#define BOARD_BTNL1_GPIO GPIO_NUM_19
#define BOARD_BTNL2_GPIO GPIO_NUM_23
#define BOARD_BTNL3_GPIO GPIO_NUM_27
#define BOARD_BTNL4_GPIO GPIO_NUM_35

#define BOARD_BUTTON_ACTIVE_LEVEL 0

#define BOARD_ADC_RAW_MIN 0
#define BOARD_ADC_RAW_MAX 4095
#define BOARD_ADC_DEFAULT_CENTER 2048
